In [1]:
import numpy as np

In [2]:
a=np.array([1,1,1,1,1])
b=np.array([2,2,2,2,2])
a*b

array([2, 2, 2, 2, 2])

In [3]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b) 

0

In [5]:
a=np.array([1,1,1,1,1])
a=a+10 
a

array([11, 11, 11, 11, 11])

In [9]:
b = [[1,2,1],[2,5,3],[8,4,6]]
b_np = np.array(b)
b_np

array([[1, 2, 1],
       [2, 5, 3],
       [8, 4, 6]])

In [10]:
b_np.ndim

2

In [14]:
b_np.size

9

In [15]:
b_np.shape

(3, 3)

In [29]:
c = np.linspace(2,20, 10)
print(c)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [34]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[0,1],[2,3],[4,5]])

C = np.dot(A,B)
C

array([[16, 22],
       [34, 49]])

In [40]:
X=np.array([[1,0,8],[2,2,9]]) 
out=X[0:2,2]
out

array([8, 9])

In [41]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])